# Generated by Django 3.2 on 2021-04-16 11:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
